version: '3.8'

services:
  appbackend:
    build:
      context: ./trelix_back
    image: trelix_back_image
    container_name: back
    ports:
      - '5000:5000'
    environment:
      MONGO_URI: "mongodb+srv://eyanehdi:Trelix123@trelix.1akuy.mongodb.net/Trelix?retryWrites=true&w=majority"

